"""empty message

Revision ID: 32543b9bd031
Revises: 
Create Date: 2024-07-02 17:11:25.566806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32543b9bd031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_to_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_img', sa.String(length=250), nullable=False))
        batch_op.drop_column('img_url')
        batch_op.drop_column('geners')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_to_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('geners', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('cover_img')

    # ### end Alembic commands ###
